#!/bin/bash
# Supabase Credentials Test Script

echo "=== Supabase Configuration Test ==="
echo ""
echo "To complete the setup, you need to configure Render with Supabase credentials."
echo ""
echo "Follow these steps:"
echo ""
echo "1. Get your Supabase credentials:"
echo "   - Go to: https://app.supabase.com"
echo "   - Select your project"
echo "   - Go to Settings → API"
echo "   - Copy the Project URL"
echo "   - Copy the 'anon' public key"
echo "   - Copy the 'service_role' secret key"
echo ""
echo "2. Set them on Render:"
echo "   - Go to: https://dashboard.render.com"
echo "   - Select 'ivorymist-mcs' service"
echo "   - Go to: Environment"
echo "   - Add/Edit these variables:"
echo "     SUPABASE_URL=<your-project-url>"
echo "     SUPABASE_ANON_KEY=<anon-key>"
echo "     SUPABASE_SERVICE_ROLE_KEY=<service-role-key>"
echo "   - Save and wait for auto-redeploy"
echo ""
echo "3. Test the backend:"
echo "   - Visit: https://ivorymist-mcs.onrender.com/api/v1/health"
echo "   - Should show: {\"status\":\"ok\"}"
echo ""
echo "4. Test the frontend:"
echo "   - Visit: https://ivorymistorderingcafes.netlify.app"
echo "   - Click: Menu"
echo "   - Should show products with stock quantities"
echo ""

